export default {
    soundDirectory: "sounds/",
    data:[
        {
            "name": "Alex",
            "description": "ARP Spoof mimicking specialist, Head of the dumb kid division.",
            "folderName": "alex/",
            "sounds": [
                ["API", "api.mp3"],
                ["ARP spoof", "arp_spoof.mp3"],
                ["As the router", "as_the_router.mp3"],
                ["The BBC website homepage", "bbc_website_homepage.mp3"],
                ["Capture the packets and display them in a readable format", "capture_the_packets.mp3"],
                ["Capturing all the information", "capturing_information.mp3"],
                ["And displays it to the screen", "displays_it_to_the_screen.mp3"],
                ["The driftnet and the URL snarf", "driftnet_and_url_snarf.mp3"],
                ["First screen", "first_screen.mp3"],
                ["Information", "information.mp3"],
                ["Initializing", "initializing.mp3"],
                ["Large database", "large_database.mp3"],
                ["MD5 hasher", "md5hasher.mp3"],
                ["Mimic the ARP Spoof", "mimic_the_arp_spoof.mp3"],
                ["Mimic the driftnet and the URL snarf", "mimic_the_driftnet_and_url_snarf.mp3"],
                ["Mimic the first screen", "mimic_the_first_screen.mp3"],
                ["Mimic the large database", "mimic_the_large_database.mp3"],
                ["Mimic the rasberry pi", "mimic_the_rasberry_pi.mp3"],
                ["Mimic the router", "mimic_the_router.mp3"],
                ["Other useful information", "other_useful_info.mp3"],
                ["Recorded by the ARP Spoof", "recorded_by_the_arp_spoof.mp3"],
                ["Recorded by the URL Snarf", "recorded_by_the_url_snarf.mp3"],
                ["Then sending packets to the server and then back to the victim", "sending_packets.mp3"],
                ["The browser", "the_browser.mp3"],
                ["The images being detected by the driftnet", "the_images_being_detected.mp3"],
                ["The packets", "the_packets.mp3"],
                ["The time", "the_time.mp3"],
                ["The website they're visiting", "the_website_visiting.mp3"],
                ["URL Snarf", "url_snarf.mp3"],
                ["Fucking he's almost dead here", "almost_dead.mp3"],
                ["AWOOOOOOOO", "awooo.mp3"],
                ["I'm like chill af", "chill_af.mp3"],
                ["I just lagged, did you see that lag?", "did_you_see_that_lag.mp3"],
                ["Why I don't wanna listen to it", "dont_wanna_listen_to_it.mp3"],
                ["Dude I..", "dude_i.mp3"],
                ["Tryna eat your arse", "eat_ass.mp3"],
                ["Explain this", "explain_this.mp3"],
                ["Find me out the front 1", "find_me_out_the_front1.mp3"],
                ["Find me out the front 2", "find_me_out_the_front2.mp3"],
                ["I really just hit three zeros I think", "hit_three_zeros.mp3"],
                ["How did he just, what even just happened?", "how_did_he_just.mp3"],
                ["Go freeze, how did I tele out?", "how_did_i_tele_out.mp3"],
                ["Is this a meme song?", "is_this_a_meme_song.mp3"],
                ["Yeah Joji is a meme", "joji_is_a_meme.mp3"],
                ["No", "no.mp3"],
                ["OOH", "oohh.mp3"],
                ["I'll play some real songs", "play_real_songs.mp3"],
                ["Ohh my here I'm recording that", "recording_that.mp3"],
                ["That's kinda hot", "thats_kinda_hot.mp3"],
                ["Wait wait wait", "wait.mp3"],
                ["What have I done this time Patty?", "what_have_i_done.mp3"],
                ["What 1", "what1.mp3"],
                ["What 2", "what2.mp3"],
                ["What 3", "what3.mp3"],
                ["What 4", "what4.mp3"],
                ["What 5", "what5.mp3"],
                ["What's wrong Patty?", "whats_wrong_patty.mp3"],
                ["Why mad right now?", "why_mad.mp3"],
                ["You ready?", "you_ready.mp3"],
            ]
        },
        {
            "name": "Patty",
            "description": "CEO - Maccas Forbes.",
            "folderName": "patty/",
            "sounds": [
                ["I always knew you were a fucking fagget", "always_knew.mp3"],
                ["Counting", "counting.mp3"],
                ["Cry more", "cry_more.mp3"],
                ["Fucking mong, I'd beat the shit out of you if I saw you in real life", "fucking_mong.mp3"],
                ["Inaudible 1", "inaudible1.mp3"],
                ["Inaudible 2", "inaudible2.mp3"],
                ["Inaudible 3", "inaudible3.mp3"],
                ["Inaudible 4", "inaudible4.mp3"],
                ["This is why I fucking hate you alex", "why_i_hate_you.mp3"],
            ]
        },
        {
            "name": "Brad",
            "description": "DOTMA - Human Resources.",
            "folderName": "brad/",
            "sounds": [
                ["Laugh 1", "laugh1.mp3"],
                ["Laugh 2", "laugh2.mp3"],
                ["Laugh 3", "laugh3.mp3"],
                ["Laugh 4", "laugh4.mp3"],
                ["Laugh 5", "laugh5.mp3"],
                ["Laugh 6", "laugh6.mp3"],
                ["Laugh 7", "laugh7.mp3"],
                ["Laugh 8", "laugh8.mp3"],
                ["Aw no censor on that one what", "no_censor.mp3"],
                ["Oh yeah", "oh_yeah.mp3"],
            ]
        },
        {
            "name": "Tony",
            "description": "Gone back to Hong Kong.",
            "folderName": "tony/",
            "sounds": [
                ["Milk", "milk.mp3"],
                ["Is a semicircle just half a circle?", "semicircle.mp3"],
                ["What's a nicker", "whats_a_nicker.mp3"],
            ]
        }
    ]
}