export default {
    soundDirectory: "sounds/",
    data:[
        {
            "name": "Alex",
            "description": "ARP Spoof mimicking specialist, Head of the dumb kid division.",
            "folderName": "alex/",
            "sounds": [
                ["API", "api.mp3"],
                ["ARP spoof", "arp_spoof.mp3"],
                ["As the router", "as_the_router.mp3"],
                ["The BBC website homepage", "bbc_website_homepage.mp3"],
                ["Capture the packets and display them in a readable format", "capture_the_packets.mp3"],
                ["Capturing all the information", "capturing_information.mp3"],
                ["And displays it to the screen", "displays_it_to_the_screen.mp3"],
                ["The driftnet and the URL snarf", "driftnet_and_url_snarf.mp3"],
                ["First screen", "first_screen.mp3"],
                ["Information", "information.mp3"],
                ["Initializing", "initializing.mp3"],
                ["Large database", "large_database.mp3"],
                ["MD5 hasher", "md5hasher.mp3"],
                ["Mimic the ARP Spoof", "mimic_the_arp_spoof.mp3"],
                ["Mimic the driftnet and the URL snarf", "mimic_the_driftnet_and_url_snarf.mp3"],
                ["Mimic the first screen", "mimic_the_first_screen.mp3"],
                ["Mimic the large database", "mimic_the_large_database.mp3"],
                ["Mimic the rasberry pi", "mimic_the_rasberry_pi.mp3"],
                ["Mimic the router", "mimic_the_router.mp3"],
                ["Other useful information", "other_useful_info.mp3"],
                ["Recorded by the ARP Spoof", "recorded_by_the_arp_spoof.mp3"],
                ["Recorded by the URL Snarf", "recorded_by_the_url_snarf.mp3"],
                ["Then sending packets to the server and then back to the victim", "sending_packets.mp3"],
                ["The browser", "the_browser.mp3"],
                ["The images being detected by the driftnet", "the_images_being_detected.mp3"],
                ["The packets", "the_packets.mp3"],
                ["The time", "the_time.mp3"],
                ["The website they're visiting", "the_website_visiting.mp3"],
                ["URL Snarf", "url_snarf.mp3"],
                ["Fucking he's almost dead here", "almost_dead.mp3"],
                ["AWOOOOOOOO", "awooo.mp3"],
                ["I'm like chill af", "chill_af.mp3"],
                ["I just lagged, did you see that lag?", "did_you_see_that_lag.mp3"],
                ["Why I don't wanna listen to it", "dont_wanna_listen_to_it.mp3"],
                ["Dude I..", "dude_i.mp3"],
                ["Tryna eat your arse", "eat_ass.mp3"],
                ["Explain this", "explain_this.mp3"],
                ["Find me out the front 1", "find_me_out_the_front1.mp3"],
                ["Find me out the front 2", "find_me_out_the_front2.mp3"],
                ["I really just hit three zeros I think", "hit_three_zeros.mp3"],
                ["How did he just, what even just happened?", "how_did_he_just.mp3"],
                ["Go freeze, how did I tele out?", "how_did_i_tele_out.mp3"],
                ["Is this a meme song?", "is_this_a_meme_song.mp3"],
                ["Yeah Joji is a meme", "joji_is_a_meme.mp3"],
                ["No", "no.mp3"],
                ["OOH", "oohh.mp3"],
                ["I'll play some real songs", "play_real_songs.mp3"],
                ["Ohh my here I'm recording that", "recording_that.mp3"],
                ["That's kinda hot", "thats_kinda_hot.mp3"],
                ["Wait wait wait", "wait.mp3"],
                ["What have I done this time Patty?", "what_have_i_done.mp3"],
                ["What 1", "what1.mp3"],
                ["What 2", "what2.mp3"],
                ["What 3", "what3.mp3"],
                ["What 4", "what4.mp3"],
                ["What 5", "what5.mp3"],
                ["What's wrong Patty?", "whats_wrong_patty.mp3"],
                ["Why mad right now?", "why_mad.mp3"],
                ["You ready?", "you_ready.mp3"],
                ["Alright, I'm Bad At The Game", "alright_im_bad_at_the_game.mp3"],
                ["Are We Play", "are_we_play.mp3"],
                ["Ayo Tony", "ayo_tony.mp3"],
                ["Body Shot? More Like Retard Shot", "body_shot_more_like_retard_shot.mp3"],
                ["Body Shots Are For Low IQ Individuals", "body_shots_are_for_low_iq_individuals.mp3"],
                ["Bok Choy", "bok_choy.mp3"],
                ["Epic Style", "epic_style.mp3"],
                ["Fire Alarm Ttime", "fire_alarm_time.mp3"],
                ["Gamer Mode On", "gamer_mode_on.mp3"],
                ["Gamers Rise Up 2", "gamers_rise_up_2.mp3"],
                ["Gamers Rise Up Moment Time", "gamers_rise_up_moment_time.mp3"],
                ["Gamers Rise Up", "gamers_rise_up.mp3"],
                ["Get More Bodyshots Idiot", "get_more_bodyshots_idiot.mp3"],
                ["God Speed Sir", "god_speed_sir.mp3"],
                ["Goodbye Shonky", "goodbye_shonky.mp3"],
                ["He Just Told Me To Sit", "he_just_told_me_to_sit.mp3"],
                ["Hello Fellow Crip", "hello_fellow_crip.mp3"],
                ["Hey Siri Do The Dab", "hey_siri_do_the_dab.mp3"],
                ["How Long Does It Take To Go On The Toilet", "how_long_does_it_take_to_go_on_the_toilet.mp3"],
                ["I Dunno What This Gay Shit Is", "i_dunno_what_this_gay_shit_is.mp3"],
                ["I Fucken Sleep What The Hell", "i_fucken_sleep_what_the_hell.mp3"],
                ["I Wonder If Siris On Tik Tok", "wonder_if_siris_on_tik_tok.mp3"],
                ["I Would Love To See Patty Get A Non Body Shot", "i_would_love_to_see_patty_get_a_non_body_shot.mp3"],
                ["I've Got Him Blocked", "i've_got_him_blocked.mp3"],
                ["I Don't Know How To Play TF2", "idk_how_to_play_tf2.mp3"],
                ["I'm Assasindie And I Approve This Message", "im_assasindie_and_i_approve_this_message.mp3"],
                ["I'm Gonna BM The Fuck Outta Patty With This", "im_gonna_bm_the_fuck_outta_patty_with_this.mp3"],
                ["I'm Not Sure What Im Doing", "im_not_sure_what_im_doing.mp3"],
                ["Imagine Bodyshotting As A Sniper", "imagine_bodyshotting_as_a_sniper.mp3"],
                ["Imagine Bodyshotting", "imagine_bodyshotting.mp3"],
                ["Imagine Not Bhopping", "imagine_not_bhopping.mp3"],
                ["Is He Playing Scout", "is_he_playing_scout.mp3"],
                ["Let's Rtd", "lets_rtd.mp3"],
                ["Low IQ", "low_iq.mp3"],
                ["Nah Bad Sensitivity", "nah_bad_sensitivity.mp3"],
                ["No Toxic Here Guys", "no_toxic_here_guys.mp3"],
                ["Oh Herro This Is Your Dog Speaking", "oh_herro_this_is_ur_dog_speaking.mp3"],
                ["Oi Donkey", "oi_donkey.mp3"],
                ["Patty Gave Me This Money", "patty_gave_me_this_money.mp3"],
                ["Patty Headshot Waiting Room", "patty_headshot_waiting_room.mp3"],
                ["Patty Is The Body Shot King", "patty_is_the_body_shot_king.mp3"],
                ["Patty Might Be Killing Me", "patty_might_be_killing_me.mp3"],
                ["Sitting On The Toilet", "sitting_on_the_toilet.mp3"],
                ["Some Fat Brad Just Appears", "some_fat_brad_just_appears.mp3"],
                ["Suck My Dick Patty", "suck_my_dick_patty.mp3"],
                ["Toxic Gaming Here", "toxic_gaming_here.mp3"],
                ["We Have Coca-Cola And Small PeePee", "we_have_cocacola_and_small_peepee.mp3"],
                ["We Up In Here", "we_up_in_here.mp3"],
                ["What A Retarded Game", "what_a_retarded_game.mp3"],
                ["What Just Happened", "what_just_happened.mp3"],
                ["Who The Fuck Is Up", "who_the_fuck_is_up.mp3"],
                ["Wtf How Toxic Can You Be", "wtf_how_toxic_can_you_be.mp3"],
                ["Yeah I Sleep", "yeah_i_sleep.mp3"],
                ["Yeah, Shonky's Bad", "yeah_shonkys_bad.mp3"],
                ["Yeah Sit", "yeah_sit.mp3"],
                ["You See Nothing Right Here", "you_see_nothing_right_here.mp3"],
            ]
        },
        {
            "name": "Patty",
            "description": "CEO - Maccas Forbes.",
            "folderName": "patty/",
            "sounds": [
                ["I always knew you were a fucking fagget", "always_knew.mp3"],
                ["Counting", "counting.mp3"],
                ["Cry more", "cry_more.mp3"],
                ["Fucking mong, I'd beat the shit out of you if I saw you in real life", "fucking_mong.mp3"],
                ["Inaudible 1", "inaudible1.mp3"],
                ["Inaudible 2", "inaudible2.mp3"],
                ["Inaudible 3", "inaudible3.mp3"],
                ["Inaudible 4", "inaudible4.mp3"],
                ["This is why I fucking hate you alex", "why_i_hate_you.mp3"],
            ]
        },
        {
            "name": "Brad",
            "description": "DOTMA - Head of Finances and Human Resources.",
            "folderName": "brad/",
            "sounds": [
                ["Laugh 1", "laugh1.mp3"],
                ["Laugh 2", "laugh2.mp3"],
                ["Laugh 3", "laugh3.mp3"],
                ["Laugh 4", "laugh4.mp3"],
                ["Laugh 5", "laugh5.mp3"],
                ["Laugh 6", "laugh6.mp3"],
                ["Laugh 7", "laugh7.mp3"],
                ["Laugh 8", "laugh8.mp3"],
                ["Aw no censor on that one what", "no_censor.mp3"],
                ["Oh yeah", "oh_yeah.mp3"],
                ["Oh, yo true","oh_yo_true.mp3"],
                ["Imagine telling people to sit","imagine_telling_people_to_sit.mp3"],
            ]
        },
        {
            "name": "Tony",
            "description": "DOTMA - CEO and Founder. Gone back to Hong Kong.",
            "folderName": "tony/",
            "sounds": [
                ["Milk", "milk.mp3"],
                ["Is a semicircle just half a circle?", "semicircle.mp3"],
                ["What's a nicker", "whats_a_nicker.mp3"],
                ["Stop calling me", "stop_calling_me.mp3"],
            ]
        },
        {
            "name": "Dotma Group",
            "description": "Also could be described as a bunch of idiots talking over each other.",
            "folderName": "group/",
            "sounds": [
                ["(Alex / Brad) No one likes BLU", "alex_brad_no_one_likes_blu.mp3"],
                ["(Alex / Brad / Siri) It understands bok choy?", "alex_brad_oh_shit_it_actually_understands_bok_choy.mp3"],
                ["(Brad / Tony) Are we play?", "brad_tony_are_we_play.mp3"],
            ]
        }
    ]
}